### ISSUE TITLE
Feeback

### ISSUE THREAD

**Issue by xhu2016** [UBC-MDS/ptoolkit#14]
Very nice format for your readMe file. I like how your tried to provide motivation for designing this package.

However, having QQ plots doesn’t make sense for p-values because the p-values are not supposed to follow any distribution. Even if there’s a pattern in the p-values, that pattern is unlikely to be statistically significant. Also, in applications, it is really bad practices to create a lot of p-values and pick the one that’s significant, so I wonder if your package will be useful. 

In addition, please provide some test ideas about testing your code.

**Comment by vmulholl** [comment]
@xhu2016 Just doing house keeping. 

As we mentioned in lab, we are doing multiple comparison which is why we plot multiple p-values. Closing this issue.
